// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptionsProd {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWRt7G4bqESrMkov4bRv5twgWrvSwokJU',
    appId: '1:148092248636:android:f15692480d08c5e966d939',
    messagingSenderId: '148092248636',
    projectId: 'leva-matrimonial---dev',
    storageBucket: 'leva-matrimonial---dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLkcUAGux8cvPc9TUqefA9_cpd9yQHyEE',
    appId: '1:148092248636:ios:a024fbad6a496d7566d939',
    messagingSenderId: '148092248636',
    projectId: 'leva-matrimonial---dev',
    storageBucket: 'leva-matrimonial---dev.appspot.com',
    androidClientId: '148092248636-8f8bp9a4gdoff1nmp1q72vav862nhavs.apps.googleusercontent.com',
    iosClientId: '148092248636-vsvhq5kgcosqsdgt9e4si7gpblci448o.apps.googleusercontent.com',
    iosBundleId: 'com.levamatrimonial.dev',
  );
}
